SELECT COUNT(NAME) 
FROM COMPANIES 
WHERE NAME LIKE '%.com' AND (CITY = 'Brussels' OR CITY = 'Bangkok'); 


SELECT TOP 5 CITY
FROM COMPANIES 
GROUP BY CITY
ORDER BY COUNT(CITY) DESC;


SELECT DISTINCT K_COMPANY
FROM CONT_COMP


SELECT COMPANIES.*, CONTACTS.*
FROM CONT_COMP
RIGHT JOIN COMPANIES
ON COMPANIES.K_COMPANY = CONT_COMP.K_COMPANY
LEFT JOIN CONTACTS
ON CONT_COMP.K_CONTACT = CONTACTS.K_CONTACT
ORDER BY COMPANIES.NAME ASC, CONTACTS.NAME DESC


SELECT COUNT(*)
FROM CONT_COMP
FULL JOIN CONTACTS
ON CONTACTS.K_CONTACT = CONT_COMP.K_CONTACT
WHERE CONTACTS.K_CONTACT IS NULL OR CONT_COMP.K_CONTACT IS NULL

